export const  semantic = {
  bgLight: "var(--black-alpha-50)",
  bgDark: "var(--black-alpha-900)",
  textLight: "var(--black-alpha-900)",
  textDark: "var(--black-alpha-50)",
  borderLight: "var(--black-alpha-100)",
  borderDark: "var(--black-alpha-900)",
  primaryLight: "var(--blue-50)",
  primaryDark: "var(--blue-900)",
  primary: "var(--blue-500)",
  secondaryLight: "var(--green-50)",
  secondaryDark: "var(--green-900)",
  secondary: "var(--green-500)",
  successLight: "var(--yellow-50)",
  successDark: "var(--yellow-900)",
  success: "var(--yellow-500)",
  warningLight: "var(--orange-50)",
  warningDark: "var(--orange-900)",
  warning: "var(--orange-500)",
  errorLight: "var(--red-50)",
  errorDark: "var(--red-900)",
  error: "var(--red-500)",
  infoLight: "var(--cyan-50)",
  infoDark: "var(--cyan-900)",
  info: "var(--cyan-500)",
};
